# This workflow checks if a PR commit has changed the size of a hello world Rust program.
# It downloads Rustc and compiles two versions of a stage0 compiler - one using the base commit
# of the PR, and one using the latest commit in the PR.
# It then uploads the two built binaries as artifacts.
name: Check binary size

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Check binary size
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Print info
        run: |
          echo "Current SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Base SHA: ${{ github.event.pull_request.base.sha }}"
      - name: Clone Rustc
        uses: actions/checkout@v3
        with:
          repository: rust-lang/rust
          fetch-depth: 1
      - name: Fetch backtrace
        run: git submodule update --init library/backtrace
      - name: Create hello world program that uses backtrace
        run: |
          printf "fn main() { panic!(); }" > foo.rs
          mkdir -p binaries
      - name: Build binary with base version of backtrace
        run: |
          printf "[llvm]\ndownload-ci-llvm = true\n\n[rust]\nincremental = false\n" > config.toml
          cd library/backtrace
          git remote add head-pr https://github.com/${{ github.event.pull_request.head.repo.full_name }}
          git fetch --all
          git checkout ${{ github.event.pull_request.base.sha }}
          cd ../..
          git add library/backtrace
          python3 x.py build library --stage 0
          cp -r ./build/x86_64-unknown-linux-gnu/stage0/bin ./build/x86_64-unknown-linux-gnu/stage0-sysroot/bin
          cp -r ./build/x86_64-unknown-linux-gnu/stage0/lib/*.so ./build/x86_64-unknown-linux-gnu/stage0-sysroot/lib
          ./build/x86_64-unknown-linux-gnu/stage0-sysroot/bin/rustc -O foo.rs -o binaries/binary-reference
      - name: Build binary with PR version of backtrace
        run: |
          cd library/backtrace
          git checkout ${{ github.event.pull_request.head.sha }}
          cd ../..
          git add library/backtrace
          rm -rf build/x86_64-unknown-linux-gnu/stage0-std
          python3 x.py build library --stage 0
          cp -r ./build/x86_64-unknown-linux-gnu/stage0/bin ./build/x86_64-unknown-linux-gnu/stage0-sysroot/bin
          cp -r ./build/x86_64-unknown-linux-gnu/stage0/lib/*.so ./build/x86_64-unknown-linux-gnu/stage0-sysroot/lib
          ./build/x86_64-unknown-linux-gnu/stage0-sysroot/bin/rustc -O foo.rs -o binaries/binary-updated
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: binaries/
# FOO
